In [5]:
import polars as pl
import torch
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
)

from src.config import PROJECT_ROOT, PROCESSED_DATA_DIR
from src.data import DatasetLoader, Preprocessor
from src.db import PBWarehouse

In [2]:
dataset_loader = DatasetLoader(PBWarehouse())
data: pl.DataFrame = dataset_loader.load_dataset()
preprocessor = Preprocessor(data=data)
data = preprocessor.preprocess()
data

✅ Loading cached dataset - Done.
✅ Loading dataset - Done.
Categorizing source column...

/tmp/ipykernel_754485/2238835076.py:4: DeprecationWarning: preprocess is deprecated. Please call (__call__) the Preprocessor instance after instantiation instead.
  data = preprocessor.preprocess()

✅ Categorizing source column - Done.
✅ Preprocessing data - Done.

shape: (36_365, 17)
┌────────────┬────────────┬────────────┬────────────┬───┬────────┬────────────┬────────────┬───────┐
│ bookmark_c ┆ favorite_c ┆ favourites ┆ follower_c ┆ … ┆ source ┆ tweet_id   ┆ user_id    ┆ views │
│ ount       ┆ ount       ┆ _count     ┆ ount       ┆   ┆ ---    ┆ ---        ┆ ---        ┆ ---   │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ i64    ┆ i64        ┆ i64        ┆ i64   │
│ i64        ┆ i64        ┆ i64        ┆ i64        ┆   ┆        ┆            ┆            ┆       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════╪════════════╪════════════╪═══════╡
│ 0          ┆ 0          ┆ 941        ┆ 39         ┆ … ┆ 0      ┆ 1269916756 ┆ 1264846057 ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 719685632  ┆ 906806786  ┆       │
│ 23         ┆ 4860       ┆ 13269      ┆ 95956      ┆ … ┆ 0      ┆ 1277976913 ┆ 23719684   ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 743503365  ┆            ┆       │
│ 0          ┆ 2          ┆ 1494       ┆ 1394       ┆ … ┆ 0      ┆ 1285714950 ┆ 1081973336 ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 896443395  ┆ 010309632  ┆       │
│ 0          ┆ 4          ┆ 2675       ┆ 49         ┆ … ┆ 0      ┆ 1284209535 ┆ 190751291  ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 561818112  ┆            ┆       │
│ 0          ┆ 2          ┆ 6          ┆ 214664     ┆ … ┆ 0      ┆ 1279563405 ┆ 121639467  ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 536325632  ┆            ┆       │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …      ┆ …          ┆ …          ┆ …     │
│ 0          ┆ 1          ┆ 2447       ┆ 468        ┆ … ┆ 0      ┆ 1269054693 ┆ 426170736  ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 323530241  ┆            ┆       │
│ 14         ┆ 3034       ┆ 532        ┆ 30305      ┆ … ┆ 0      ┆ 1274010135 ┆ 2904953395 ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 606620161  ┆            ┆       │
│ 0          ┆ 0          ┆ 3071       ┆ 54046      ┆ … ┆ 0      ┆ 1284986922 ┆ 14870085   ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 490720257  ┆            ┆       │
│ 0          ┆ 9          ┆ 48         ┆ 195        ┆ … ┆ 0      ┆ 1269779646 ┆ 1237067469 ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 897258496  ┆ 765804037  ┆       │
│ 0          ┆ 1          ┆ 11259      ┆ 607        ┆ … ┆ 0      ┆ 1268331100 ┆ 333534103  ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 281008128  ┆            ┆       │
└────────────┴────────────┴────────────┴────────────┴───┴────────┴────────────┴────────────┴───────┘

In [7]:
import polars as pl

finetuned_data = pl.read_csv(PROCESSED_DATA_DIR / "hatebert-finetuned.csv")
finetuned_data

shape: (36_364, 3)
┌─────────────────────────────────┬─────────────────────┬────────────┐
│ text                            ┆ tweet_id            ┆ is_hateful │
│ ---                             ┆ ---                 ┆ ---        │
│ str                             ┆ i64                 ┆ i64        │
╞═════════════════════════════════╪═════════════════════╪════════════╡
│ @TRCdocumentary @Blklivesmatte… ┆ 1269916756719685632 ┆ 1          │
│ @terrycrews @jonathanwsabin Th… ┆ 1277976913743503365 ┆ 1          │
│ Join Bernie and Sunrise leader… ┆ 1285714950896443395 ┆ 1          │
│ @prageru It's not the women's … ┆ 1284209535561818112 ┆ 1          │
│ A #BlackLivesMatter protest in… ┆ 1279563405536325632 ┆ 1          │
│ …                               ┆ …                   ┆ …          │
│ I curated a list of black-owne… ┆ 1269054693323530241 ┆ 1          │
│ Defund. Disarm. Dismantle. #De… ┆ 1274010135606620161 ┆ 1          │
│ Bill Nye with the mic drop. #S… ┆ 1284986922490720257 ┆ 1          │
│ Shoutout to Keith Lee with the… ┆ 1269779646897258496 ┆ 1          │
│ Powerful words @amayapapaya13 … ┆ 1268331100281008128 ┆ 1          │
└─────────────────────────────────┴─────────────────────┴────────────┘

In [8]:
for row in finetuned_data.iter_rows(named=True):
    data = data.with_columns(
        pl.when(pl.col("tweet_id") == row["tweet_id"])
          .then(pl.lit(row["is_hateful"]))
          .otherwise(pl.col("is_hateful"))
          .alias("is_hateful")
    )

data.write_csv(PROCESSED_DATA_DIR / "finetuned_dataset_cache.csv")

In [9]:
data

shape: (36_365, 17)
┌────────────┬────────────┬────────────┬────────────┬───┬────────┬────────────┬────────────┬───────┐
│ bookmark_c ┆ favorite_c ┆ favourites ┆ follower_c ┆ … ┆ source ┆ tweet_id   ┆ user_id    ┆ views │
│ ount       ┆ ount       ┆ _count     ┆ ount       ┆   ┆ ---    ┆ ---        ┆ ---        ┆ ---   │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆   ┆ i64    ┆ i64        ┆ i64        ┆ i64   │
│ i64        ┆ i64        ┆ i64        ┆ i64        ┆   ┆        ┆            ┆            ┆       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════╪════════════╪════════════╪═══════╡
│ 0          ┆ 0          ┆ 941        ┆ 39         ┆ … ┆ 0      ┆ 1269916756 ┆ 1264846057 ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 719685632  ┆ 906806786  ┆       │
│ 23         ┆ 4860       ┆ 13269      ┆ 95956      ┆ … ┆ 0      ┆ 1277976913 ┆ 23719684   ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 743503365  ┆            ┆       │
│ 0          ┆ 2          ┆ 1494       ┆ 1394       ┆ … ┆ 0      ┆ 1285714950 ┆ 1081973336 ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 896443395  ┆ 010309632  ┆       │
│ 0          ┆ 4          ┆ 2675       ┆ 49         ┆ … ┆ 0      ┆ 1284209535 ┆ 190751291  ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 561818112  ┆            ┆       │
│ 0          ┆ 2          ┆ 6          ┆ 214664     ┆ … ┆ 0      ┆ 1279563405 ┆ 121639467  ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 536325632  ┆            ┆       │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …      ┆ …          ┆ …          ┆ …     │
│ 0          ┆ 1          ┆ 2447       ┆ 468        ┆ … ┆ 0      ┆ 1269054693 ┆ 426170736  ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 323530241  ┆            ┆       │
│ 14         ┆ 3034       ┆ 532        ┆ 30305      ┆ … ┆ 0      ┆ 1274010135 ┆ 2904953395 ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 606620161  ┆            ┆       │
│ 0          ┆ 0          ┆ 3071       ┆ 54046      ┆ … ┆ 0      ┆ 1284986922 ┆ 14870085   ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 490720257  ┆            ┆       │
│ 0          ┆ 9          ┆ 48         ┆ 195        ┆ … ┆ 0      ┆ 1269779646 ┆ 1237067469 ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 897258496  ┆ 765804037  ┆       │
│ 0          ┆ 1          ┆ 11259      ┆ 607        ┆ … ┆ 0      ┆ 1268331100 ┆ 333534103  ┆ 0     │
│            ┆            ┆            ┆            ┆   ┆        ┆ 281008128  ┆            ┆       │
└────────────┴────────────┴────────────┴────────────┴───┴────────┴────────────┴────────────┴───────┘

In [3]:
MODEL_NAME = "Hate-speech-CNERG/bert-base-uncased-hatexplain"
# HATEBERT on Hugging Face

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, attn_implementation="eager"
)

model.load_state_dict(torch.load(PROJECT_ROOT / "finetuned_model-32-epochs.pth"))
model.eval()

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=3, bias=True)
)

In [ ]:
df.with_columns(
    pl.col("text").map_elements(lambda x: classify_text(x), return_dtype=pl.Int8).alias("is_hateful")
)