In [1]:
import mlflow
import polars as pl
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score
from torch.utils.data import DataLoader, Dataset
from torchinfo import summary
from tqdm.notebook import tqdm
from transformers import AutoModel, AutoTokenizer
from transformers.models.bert.modeling_bert import BertModel
from mlflow.models import infer_signature

# Types
from transformers.models.bert.tokenization_bert_fast import BertTokenizerFast

import matplotlib.pyplot as plt
from src.config import MPL_STYLE_DIR
from src.db import PBWarehouse
from src.models import Tweet

mlflow.set_tracking_uri("http://192.168.100.203:5000")
mlflow.set_experiment("[CAPSTONE-2] bert-finetuning")
plt.style.use(MPL_STYLE_DIR / "iragca_ml.mplstyle")

warehouse = PBWarehouse()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

2025-07-06 14:19:43.194 | INFO     | src.config:<module>:25 - Loaded environment variables from /home/iragca/Documents/github/capstone-project-2/.env
2025-07-06 14:19:43.194 | INFO     | src.config:<module>:59 - PROJECT_ROOT: /home/iragca/Documents/github/capstone-project-2
2025-07-06 14:19:43.195 | INFO     | src.config:<module>:60 - DATA_DIR: /home/iragca/Documents/github/capstone-project-2/data

device(type='cuda')

In [2]:
data = warehouse.client.collection("tweets_v2").get_full_list(
    query_params={
        "filter": "(has_blm_hashtag = true || is_reply_to_blm = true) && is_annotated = true"
    }
)
tweets: list[Tweet] = [Tweet(**r.__dict__) for r in data]

In [3]:
df = pl.DataFrame(
    [t.model_dump() for t in tweets],
    schema={
        "tweet_id": pl.Utf8,
        "text": pl.Utf8,
        "status_link": pl.Utf8,
        "user_id": pl.Utf8,
        "is_extremist": pl.Boolean,
        "is_annotated": pl.Boolean,
        "bookmark_count": pl.Int64,
        "views": pl.Int64,
        "retweet_count": pl.Int64,
        "favorite_count": pl.Int64,
        "reply_count": pl.Int64,
        "quote_count": pl.Int64,
        "in_reply_to_status_id": pl.Utf8,
        "conversation_id": pl.Utf8,
        "retweet_tweet_id": pl.Utf8,
        "quoted_status_id": pl.Utf8,
        "community_note": pl.Utf8,
        "language": pl.Utf8,
        "source": pl.Utf8,
        "creation_date": pl.Utf8,
        "has_blm_hashtag": pl.Boolean,
        "fetched_replies": pl.Boolean,
        "is_reply_to_blm": pl.Boolean,
    },
).with_columns(
    pl.col("creation_date").str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S%.3fZ")
)
df

shape: (70, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ tweet_id  ┆ text      ┆ status_li ┆ user_id   ┆ … ┆ creation_ ┆ has_blm_h ┆ fetched_r ┆ is_reply │
│ ---       ┆ ---       ┆ nk        ┆ ---       ┆   ┆ date      ┆ ashtag    ┆ eplies    ┆ _to_blm  │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆           ┆   ┆ datetime[ ┆ bool      ┆ bool      ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ ms]       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 128644084 ┆ finally.  ┆ https://x ┆ 19804476  ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 677922406 ┆ thank you ┆ .com/Jane ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│ 4         ┆ #BLM      ┆ GPhoto/st ┆           ┆   ┆ 23:19:33  ┆           ┆           ┆          │
│           ┆           ┆ atu…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128643632 ┆ Dr. Fauci ┆ https://x ┆ 942852873 ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 501769421 ┆ throws    ┆ .com/Kevi ┆ 762824192 ┆   ┆ 3         ┆           ┆           ┆          │
│ 5         ┆ out the   ┆ nBarryKC/ ┆           ┆   ┆ 23:01:35  ┆           ┆           ┆          │
│           ┆ first…    ┆ sta…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644624 ┆ Ok so @Ni ┆ https://x ┆ 171610230 ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 793570918 ┆ agaraRegi ┆ .com/Gran ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│ 7         ┆ on just   ┆ tRants/st ┆           ┆   ┆ 23:41:01  ┆           ┆           ┆          │
│           ┆ fini…     ┆ atu…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644687 ┆ @RyanShea ┆ https://x ┆ 123233898 ┆ … ┆ 2020-07-2 ┆ false     ┆ true      ┆ true     │
│ 506366464 ┆ d Hey!? A ┆ .com/ReiR ┆ 139772928 ┆   ┆ 3         ┆           ┆           ┆          │
│ 0         ┆ Bosox     ┆ ei720dxcu ┆ 1         ┆   ┆ 23:43:30  ┆           ┆           ┆          │
│           ┆ cap? …    ┆ te/…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644660 ┆ Imma just ┆ https://x ┆ 119706034 ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 746295705 ┆ set this  ┆ .com/SheT ┆ 706210406 ┆   ┆ 3         ┆           ┆           ┆          │
│ 6         ┆ right     ┆ alksSeXXX ┆ 4         ┆   ┆ 23:42:26  ┆           ┆           ┆          │
│           ┆ here …    ┆ /st…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 128644374 ┆ So proud  ┆ https://x ┆ 154714175 ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 063939584 ┆ of my     ┆ .com/Jinn ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│ 0         ┆ daughter  ┆ ieSpiegle ┆           ┆   ┆ 23:31:03  ┆           ┆           ┆          │
│           ┆ who’s …   ┆ r/s…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644806 ┆ I had     ┆ https://x ┆ 16073596  ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 608663347 ┆ held off  ┆ .com/Gart ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│ 2         ┆ sharing   ┆ hGodsman/ ┆           ┆   ┆ 23:48:14  ┆           ┆           ┆          │
│           ┆ this ph…  ┆ sta…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644215 ┆ #NowPlayi ┆ https://x ┆ 317869483 ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 375813836 ┆ ng Gotta  ┆ .com/Tuni ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│ 8         ┆ Be -      ┆ tupRadio/ ┆           ┆   ┆ 23:24:45  ┆           ┆           ┆          │
│           ┆ Reflexi…  ┆ sta…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644246 ┆ I like    ┆ https://x ┆ 21344364  ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 102863872 ┆ the mlb   ┆ .com/pdav ┆           ┆   ┆ 3         ┆           ┆           ┆          │
│ 0         ┆ backwards ┆ eb/status ┆           ┆   ┆ 23:25:58  ┆           ┆           ┆          │
│           ┆ #BLM …    ┆ /12…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 128644148 ┆ Livestrea ┆ https://x ┆ 128282552 ┆ … ┆ 2020-07-2 ┆ true      ┆ true      ┆ false    │
│ 744682291 ┆ m is      ┆ .com/agai ┆ 241906074 ┆   ┆ 3         ┆           ┆           ┆          │
│ 3         ┆ working!  ┆ nstthesys ┆ 1         ┆   ┆ 23:22:06  ┆           ┆           ┆          │
│           ┆           ┆ tm/…      ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ https…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
train_df = df.select(["text", "is_extremist"])
dataset = mlflow.data.from_pandas(
    train_df.to_pandas(), name="BLM Tweets", targets="is_extremist"
)

train_df

shape: (70, 2)
┌─────────────────────────────────┬──────────────┐
│ text                            ┆ is_extremist │
│ ---                             ┆ ---          │
│ str                             ┆ bool         │
╞═════════════════════════════════╪══════════════╡
│ finally. thank you #BLM         ┆ false        │
│ Dr. Fauci throws out the first… ┆ false        │
│ Ok so @NiagaraRegion just fini… ┆ false        │
│ @RyanShead Hey!? A Bosox cap? … ┆ false        │
│ Imma just set this right here … ┆ false        │
│ …                               ┆ …            │
│ So proud of my daughter who’s … ┆ false        │
│ I had held off sharing this ph… ┆ true         │
│ #NowPlaying Gotta Be - Reflexi… ┆ false        │
│ I like the mlb backwards #BLM … ┆ false        │
│ Livestream is working!          ┆ false        │
│                                 ┆              │
│ https…                          ┆              │
└─────────────────────────────────┴──────────────┘

In [5]:
X_validation, X_holdout, y_validation, y_holdout = train_test_split(
    train_df["text"],
    train_df["is_extremist"],
    test_size=0.2,
    random_state=42,
)

X_train, X_test, y_train, y_test = train_test_split(
    X_validation,
    y_validation,
    test_size=0.2,
    random_state=42,
)

print(
    f"Train: {len(X_train)}, Test: {len(X_test)}, Validation: {len(X_validation)}, Holdout: {len(X_holdout)}"
)
print(
    f"Train ratio: {len(X_train) / len(df):.2f}, Test ratio: {len(X_test) / len(df):.2f}, Validation ratio: {len(X_validation) / len(df):.2f}, Holdout ratio: {len(X_holdout) / len(df):.2f}"
)

Train: 44, Test: 12, Validation: 56, Holdout: 14
Train ratio: 0.63, Test ratio: 0.17, Validation ratio: 0.80, Holdout ratio: 0.20

In [6]:
bert_model_name = "google-bert/bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(bert_model_name)
bert_model = AutoModel.from_pretrained(bert_model_name)

In [7]:
class ExtremistDataset(Dataset):
    def __init__(self, X: pl.Series, y: pl.Series, bert_tokenizer: BertTokenizerFast):
        assert isinstance(X, pl.Series), "X must be a polars DataFrame"
        assert isinstance(y, pl.Series), "y must be a polars DataFrame"
        assert len(X) == len(y), "X and y must have the same length"
        assert "text" == X.name, "X must contain a 'text' column for the tweets"
        assert "is_extremist" == y.name, "y must contain an 'is_extremist' column"
        assert isinstance(bert_tokenizer, BertTokenizerFast), (
            "tokenizer must be an instance of AutoTokenizer"
        )
        self.X = [
            bert_tokenizer(
                x,
                max_length=100,
                truncation=True,
                padding="max_length",
                return_tensors="pt",
            )
            for x in X
        ]

        self.y = y.to_torch().to(torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        x = self.X[idx]
        y = self.y[idx]
        return x, y


training_dataset = ExtremistDataset(X_train, y_train, tokenizer)
validation_dataset = ExtremistDataset(X_test, y_test, tokenizer)
holdout_dataset = ExtremistDataset(X_holdout, y_holdout, tokenizer)

In [8]:
params = {
    "BATCH_SIZE": 32,
    "EPOCHS": 10,
    "LEARNING_RATE": 1e-4,
    "DROPOUT_RATE": 0.25,
}

In [9]:
train_dataloader = DataLoader(
    training_dataset, batch_size=params["BATCH_SIZE"], shuffle=True
)
validation_dataloader = DataLoader(
    validation_dataset, batch_size=params["BATCH_SIZE"], shuffle=False
)
holdout_dataloader = DataLoader(
    holdout_dataset, batch_size=params["BATCH_SIZE"], shuffle=False
)

# Training

In [10]:
class ExtremismDetector(nn.Module):
    def __init__(self, bert_model: BertModel, dropout_rate: float):
        super(ExtremismDetector, self).__init__()
        assert isinstance(bert_model, BertModel), (
            "bert_model must be an instance of AutoModel"
        )

        self.bert = bert_model
        self.linear1 = nn.Linear(bert_model.config.hidden_size, 384)
        self.dropout = nn.Dropout(dropout_rate)
        self.linear2 = nn.Linear(384, 1)
        self.activation = nn.Sigmoid()

    def forward(self, input_ids, attention_mask):
        pooled_output = self.bert(
            input_ids=input_ids, attention_mask=attention_mask, return_dict=False
        )[0][:, 0]

        h = self.linear1(pooled_output)
        h = self.dropout(h)
        h = self.linear2(h)
        h = self.activation(h)

        return h

In [11]:
for param in bert_model.parameters():
    param.requires_grad = False

model = ExtremismDetector(bert_model, params["DROPOUT_RATE"])
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=params["LEARNING_RATE"])


input_data = {
    "input_ids": training_dataset[0][0]["input_ids"],
    "attention_mask": training_dataset[0][0]["attention_mask"],
}

example_output = torch.tensor([0.95])  # e.g., probability output
# Convert to numpy for signature inference
example_input_numpy = {
    k: v.numpy() for k, v in training_dataset[0][0].items()
}
example_output_numpy = example_output.numpy()

# Create the signature
signature = infer_signature(example_input_numpy, example_output_numpy)

In [12]:
with mlflow.start_run(log_system_metrics=True) as run:
    mlflow.log_params(params)
    mlflow.log_input(dataset, context="training", tags={"source": "Twitter / X"})
    mlflow.set_tag("purpose", "configuring")
    mlflow.set_tag("framework", "pytorch")
    mlflow.set_tag("task-type", "text classification")
    mlflow.set_tag("task", "extremism detection")

    with open("model_summary.txt", "w") as f:
        f.write(
            str(
                summary(
                    model,
                    device=str(device),
                    input_data=input_data,
                    col_names=[
                        "input_size",
                        "output_size",
                        "num_params",
                        "params_percent",
                        "mult_adds",
                        "kernel_size",
                    ],
                )
            )
        )

    model.to("cpu")
    with open("model_architecture.txt", "w") as f:
        f.write(str(model))

    mlflow.pytorch.log_model(
        model,
        name="Sarcasm Detector",
        signature=signature,
        extra_files=["model_summary.txt", "model_architecture.txt"],
    )
    model.to(device)
    bert_model.to(device)
    for epoch in tqdm(range(params["EPOCHS"]), desc="Training epochs", unit="epoch"):
        ## Train and validate the model
        model.train()
        total_loss_train = 0
        total_loss_validation = 0

        all_preds_train = []
        all_labels_train = []

        all_preds_validation = []
        all_labels_validation = []

        for inputs, labels in tqdm(
            train_dataloader,
            desc=f"Epoch {epoch + 1}/{params['EPOCHS']} - Training batches",
            unit="batch",
            leave=False,
        ):
            inputs = inputs.to(device)
            labels = labels.to(device)

            predictions = model(
                input_ids=inputs["input_ids"].squeeze(1),
                attention_mask=inputs["attention_mask"].squeeze(1),
            ).squeeze(1)

            batch_loss = criterion(predictions, labels)
            total_loss_train += batch_loss.item()

            all_preds_train.extend(predictions.round().detach().cpu().numpy())
            all_labels_train.extend(labels.detach().cpu().numpy())

            batch_loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        with torch.no_grad():
            model.eval()
            for inputs, labels in tqdm(
                validation_dataloader,
                desc=f"Epoch {epoch + 1}/{params['EPOCHS']} - Validation batches",
                unit="batch",
                leave=False,
            ):
                inputs = inputs.to(device)
                labels = labels.to(device)

                predictions = model(
                    input_ids=inputs["input_ids"].squeeze(1),
                    attention_mask=inputs["attention_mask"].squeeze(1),
                ).squeeze(1)

                batch_loss = criterion(predictions, labels)
                total_loss_validation += batch_loss.item()

                all_preds_validation.extend(predictions.round().detach().cpu().numpy())
                all_labels_validation.extend(labels.detach().cpu().numpy())

        mlflow.log_metrics(
            {
                "train_loss": total_loss_train / len(train_dataloader),
                "train_accuracy": accuracy_score(all_labels_train, all_preds_train),
                "train_f1": f1_score(
                    all_labels_train, all_preds_train, zero_division=0
                ),
                "train_precision": precision_score(
                    all_labels_train, all_preds_train, zero_division=0
                ),
                "train_recall": recall_score(
                    all_labels_train, all_preds_train, zero_division=0
                ),
                "validation_loss": total_loss_validation / len(validation_dataloader),
                "validation_accuracy": accuracy_score(
                    all_labels_validation, all_preds_validation
                ),
                "validation_precision": precision_score(
                    all_labels_validation, all_preds_validation, zero_division=0
                ),
                "validation_recall": recall_score(
                    all_labels_validation, all_preds_validation, zero_division=0
                ),
                "validation_f1": f1_score(
                    all_labels_validation, all_preds_validation, zero_division=0
                ),
            },
            step=epoch,
        )

2025/07/06 14:19:46 INFO mlflow.system_metrics.system_metrics_monitor: Started monitoring system metrics.
2025/07/06 14:19:46 WARNING mlflow.system_metrics.metrics.gpu_monitor: Encountered error Not Supported when trying to collect GPU power usage metrics.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2025/07/06 14:19:52 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2025/07/06 14:19:56 WARNING mlflow.system_metrics.metrics.gpu_monitor: Encountered error Not Supported when trying to collect GPU power usage metrics.

Training epochs:   0%|          | 0/10 [00:00<?, ?epoch/s]

Epoch 1/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 1/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 2/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 2/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 3/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 3/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 4/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 4/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 5/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 5/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 6/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 6/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 7/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 7/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 8/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 8/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 9/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

2025/07/06 14:20:06 WARNING mlflow.system_metrics.metrics.gpu_monitor: Encountered error Not Supported when trying to collect GPU power usage metrics.

Epoch 9/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

Epoch 10/10 - Training batches:   0%|          | 0/2 [00:00<?, ?batch/s]

Epoch 10/10 - Validation batches:   0%|          | 0/1 [00:00<?, ?batch/s]

2025/07/06 14:20:08 INFO mlflow.system_metrics.system_metrics_monitor: Stopping system metrics monitoring...
2025/07/06 14:20:08 INFO mlflow.system_metrics.system_metrics_monitor: Successfully terminated system metrics monitoring!

🏃 View run classy-fly-276 at: http://192.168.100.203:5000/#/experiments/5/runs/32cadf1ba55e4a37b7d442b3a4fb4d25
🧪 View experiment at: http://192.168.100.203:5000/#/experiments/5

# Testing

In [13]:
with mlflow.start_run(log_system_metrics=True) as run:
    mlflow.log_params(params)
    mlflow.log_input(dataset, context="testing", tags={"source": "Twitter / X"})
    mlflow.set_tag("purpose", "configuring")
    mlflow.set_tag("framework", "pytorch")
    mlflow.set_tag("task-type", "text classification")
    mlflow.set_tag("task", "extremism detection")

    model.to(device)
    with open("model_summary.txt", "w") as f:
        f.write(
            str(
                summary(
                    model,
                    device=str(device),
                    input_data=input_data,
                    col_names=[
                        "input_size",
                        "output_size",
                        "num_params",
                        "params_percent",
                        "mult_adds",
                        "kernel_size",
                    ],
                )
            )
        )

    model.to("cpu")
    with open("model_architecture.txt", "w") as f:
        f.write(str(model))


    mlflow.pytorch.log_model(
        model,
        name="Sarcasm Detector",
        signature=signature,
        extra_files=["model_summary.txt", "model_architecture.txt"],
    )

    model.to(device)
    bert_model.to(device)

    ## Evaluate on holdout set
    test_loss = 0.0
    all_preds_holdout = []
    all_labels_holdout = []

    with torch.no_grad():
        model.eval()
        for inputs, labels in tqdm(
            holdout_dataloader,
            desc="Holdout batches",
            unit="batch",
            leave=False,
        ):
            inputs = inputs.to(device)
            labels = labels.to(device)

            predictions = model(
                input_ids=inputs["input_ids"].squeeze(1),
                attention_mask=inputs["attention_mask"].squeeze(1),
            ).squeeze(1)

            batch_loss = criterion(predictions, labels)
            test_loss += batch_loss.item()

            all_preds_holdout.extend(predictions.round().detach().cpu().numpy())
            all_labels_holdout.extend(labels.detach().cpu().numpy())

        mlflow.log_metrics(
            {
                "holdout_loss": test_loss / len(holdout_dataloader),
                "holdout_accuracy": accuracy_score(
                    all_labels_holdout, all_preds_holdout
                ),
                "holdout_precision": precision_score(
                    all_labels_holdout, all_preds_holdout, zero_division=0
                ),
                "holdout_recall": recall_score(
                    all_labels_holdout, all_preds_holdout, zero_division=0
                ),
                "holdout_f1": f1_score(
                    all_labels_holdout, all_preds_holdout, zero_division=0
                ),
            }
        )

2025/07/06 14:20:08 INFO mlflow.system_metrics.system_metrics_monitor: Started monitoring system metrics.
2025/07/06 14:20:08 WARNING mlflow.system_metrics.metrics.gpu_monitor: Encountered error Not Supported when trying to collect GPU power usage metrics.

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

2025/07/06 14:20:13 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2025/07/06 14:20:18 WARNING mlflow.system_metrics.metrics.gpu_monitor: Encountered error Not Supported when trying to collect GPU power usage metrics.

Holdout batches:   0%|          | 0/1 [00:00<?, ?batch/s]

2025/07/06 14:20:21 INFO mlflow.system_metrics.system_metrics_monitor: Stopping system metrics monitoring...
2025/07/06 14:20:21 INFO mlflow.system_metrics.system_metrics_monitor: Successfully terminated system metrics monitoring!

🏃 View run agreeable-sponge-893 at: http://192.168.100.203:5000/#/experiments/5/runs/51aa5bf34313499ca3b11ea22a8aed3f
🧪 View experiment at: http://192.168.100.203:5000/#/experiments/5